In [1]:
import gdown
gdown.download('https://bit.ly/3GisL6J', 'ns_book4.csv', quiet=False)

Downloading...
From: https://bit.ly/3GisL6J
To: c:\til\ns_book4.csv
100%|██████████| 55.5M/55.5M [00:04<00:00, 11.5MB/s]

'ns_book4.csv'

In [2]:
import pandas as pd
ns_book4 = pd.read_csv('ns_book4.csv', low_memory=False)
ns_book4.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0.0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0.0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0.0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0.0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0.0,2021-03-19

- `info()` 메서드: 데이터프레임 정보를 요약해서 출력해주는 함수
- 열마다 `NaN`이 아닌 값이 몇 개나 있는지 확인 가능

In [3]:
ns_book4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 384591 entries, 0 to 384590
Data columns (total 13 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   번호       384591 non-null  int64
 1   도서명      384188 non-null  object
 2   저자       384393 non-null  object
 3   출판사      379950 non-null  object
 4   발행년도     384577 non-null  object
 5   ISBN     384591 non-null  object
 6   세트 ISBN  56576 non-null   object
 7   부가기호     310386 non-null  object
 8   권        63378 non-null   object
 9   주제분류번호   364727 non-null  object
 10  도서권수     384591 non-null  int64
 11  대출건수     384591 non-null  float64
 12  등록일자     384591 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 38.1+ MB

- `memory_usage` 매개변수를 `deep`으론 지정하면 정확한 메모리 사용량을 얻을 수 있음

In [4]:
ns_book4.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 384591 entries, 0 to 384590
Data columns (total 13 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   번호       384591 non-null  int64
 1   도서명      384188 non-null  object
 2   저자       384393 non-null  object
 3   출판사      379950 non-null  object
 4   발행년도     384577 non-null  object
 5   ISBN     384591 non-null  object
 6   세트 ISBN  56576 non-null   object
 7   부가기호     310386 non-null  object
 8   권        63378 non-null   object
 9   주제분류번호   364727 non-null  object
 10  도서권수     384591 non-null  int64
 11  대출건수     384591 non-null  float64
 12  등록일자     384591 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 234.0 MB

- `isna()` 메서드: 각 행이 비어 있는지를 나타내는 `boolean` 배열을 반환하는 메서드
- `NaN`이면 `True`를 반환

In [5]:
ns_book4.isna().head(5)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,False,False,False,False,False,False,True,True,True,True,False,False,False
1,False,False,False,False,False,False,True,True,True,True,False,False,False
2,False,False,False,False,False,False,True,True,True,True,False,False,False
3,False,False,False,False,False,False,True,True,True,True,False,False,False
4,False,False,False,False,False,False,True,True,True,True,False,False,False

In [ ]:
# 비어있는 행의 개수를 얻을 수 있음
ns_book4.isna().sum()

번호              0
도서명           403
저자            198
출판사          4641
발행년도           14
ISBN            0
세트 ISBN    328015
부가기호        74205
권          321213
주제분류번호      19864
도서권수            0
대출건수            0
등록일자            0
dtype: int64

In [7]:
# notna(): isna() 메서드와 반대
ns_book4.notna().sum()

번호         384591
도서명        384188
저자         384393
출판사        379950
발행년도       384577
ISBN       384591
세트 ISBN     56576
부가기호       310386
권           63378
주제분류번호     364727
도서권수       384591
대출건수       384591
등록일자       384591
dtype: int64

- 데이터프레임의 정수를 저장하는 열에 `None`을 입력하면 `NaN`으로 인식

In [8]:
ns_book4.loc[0, '도서권수'] = None
ns_book4['도서권수'].isna().sum()

1

In [ ]:
# 판다스는 NaN을 특별한 실수값으로 저장하므로 열의 데이터 타입이 int64 -> float64로 변경됨
ns_book4.head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,NaN,0.0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1.0,0.0,2021-03-19

- `astype()` 메서드: 열의 데이터 타입을 지정하는 메서드

In [ ]:
ns_book4.loc[0, '도서권수'] = 1

# {열 이름:데이터 타입} 형식의 딕셔너리로 지정
ns_book4 = ns_book4.astype({'도서권수':'int64', '대출건수':'int64'})
ns_book4.head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19

- 문자열 타입을 저장하는 열에 `None`을 입력하면 `NaN`이 아니라, `None`으로 표시
- `NaN`으로 동일하게 표시하려면 `np.nan`을 사용

In [12]:
import numpy as np
ns_book4.loc[0,'부가기호'] = np.nan
ns_book4.head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19

- 누락된 값을 다른 값으로 변경하는 방법  
- 1) `isna()` 메서드로 `boolean` 배열을 얻고, `loc()` 메서드를 통해 누락된 값을 빈 문자열로 변경
- 2) `fillna()` 메서드에 원하는 값을 전달
- 3) `replace()` 메서드 사용
    - 첫 번째 매개변수는 원래 값, 두 번째 매개변수는 새로운 값 전달

In [ ]:
# 방법 1
set_isbn_na_rows = ns_book4['세트 ISBN'].isna()
ns_book4.loc[set_isbn_na_rows, '세트 ISBN'] = ''
ns_book4['세트 ISBN'].isna().sum()

0

In [ ]:
# 방법 2
ns_book4.fillna('없음').isna().sum()    # ns_book4의 모든 NaN을 '없음' 문자열로 변경

번호         0
도서명        0
저자         0
출판사        0
발행년도       0
ISBN       0
세트 ISBN    0
부가기호       0
권          0
주제분류번호     0
도서권수       0
대출건수       0
등록일자       0
dtype: int64

In [16]:
# 특정 열과 바꾸려는 값을 딕셔너리 형태로 지정 가능
ns_book4.fillna({'부가기호':'없음'}).isna().sum()

번호              0
도서명           403
저자            198
출판사          4641
발행년도           14
ISBN            0
세트 ISBN         0
부가기호            0
권          321213
주제분류번호      19864
도서권수            0
대출건수            0
등록일자            0
dtype: int64

In [17]:
ns_book4.replace(np.nan, '없음').isna().sum()

번호         0
도서명        0
저자         0
출판사        0
발행년도       0
ISBN       0
세트 ISBN    0
부가기호       0
권          0
주제분류번호     0
도서권수       0
대출건수       0
등록일자       0
dtype: int64

In [ ]:
# 바꾸려는 값이 여러 개일 때는 리스트 형식으로 전달
ns_book4.replace([np.nan, '2021'], ['없음', '21']).head(2)  # np.nan을 없음, '2021'을 21로 변경

# 딕셔너리 형태로도 지정 가능
# {np.nan:'없음', '2021':'21'}

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,21,9788937444319,,없음,없음,없음,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,21,9791190123969,,없음,없음,없음,1,0,2021-03-19

- 정규표현식: 문자열 패턴을 찾아서 대체하기 위한 규칙의 모음  

- `\d`: 숫자를 나타내는 기호  
- `\d\d\d\d`: 4자리 숫자를 나타내는 기호
- 그룹으로 묶고 싶을 때는 () 사용 / `\d\d(\d\d)`  
- 그룹을 지칭하고 싶을 때는 `\1`, `\2` 처럼 표현  
- 정규표현식을 사용할 땐 `regex` 매개변수를 `True`로 지정  
- `r` 문자는 원시 문자열을 만드는 기능을 하므로 `\`를 이스케이프 문자가 아닌 있는 그대로 처리하므로 정규표현식을 만들 때 사용
- `\d{2}`는 `\d\d`와 동일한 의미 -> 중괄호를 사용하여 개수 지정 가능

In [ ]:
# 2018, 2021 ... 4자리 연도를 2자리 연도로 변경
ns_book4.replace({'발행년도':{r'\d{2}(\d{2})':r'\1'}}, regex=True)[100:102]

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
100,101,No라고 말할 줄 아는 남편과 아내 - 개정판,"헨리 클라우드, 존 타운센드 (지은이), 김진웅 (옮긴이)",좋은씨앗,18,9788958743019,,NaN,NaN,234.9,1,1,2021-03-15
101,102,"D2C 레볼루션 - 스타트업부터 글로벌 기업까지, 마켓 체인저의 필수 전략","로런스 인그래시아 (지은이), 안기순 (옮긴이)",부키,21,9788960518483,,NaN,NaN,325.1,1,0,2021-03-15

- `.`: 어떤 문자에도 대응하는 정규 표현식 문자  
- `*`: 반복 개수를 정확히 알 수 없을 때 사용  
- `\s`: 공백 문자를 나타내는 정규 표현식

In [ ]:
# '(지은이)', '(옮긴이)'를 삭제하여 추출
ns_book4.replace({'저자':{r'(.*)\s\(지은이\)(.*)\s\(옮긴이\)': r'\1\2'}, '발행년도':{r'\d{2}(\d{2})':r'\1'}}, regex=True)[100:102]

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
100,101,No라고 말할 줄 아는 남편과 아내 - 개정판,"헨리 클라우드, 존 타운센드, 김진웅",좋은씨앗,18,9788958743019,,NaN,NaN,234.9,1,1,2021-03-15
101,102,"D2C 레볼루션 - 스타트업부터 글로벌 기업까지, 마켓 체인저의 필수 전략","로런스 인그래시아, 안기순",부키,21,9788960518483,,NaN,NaN,325.1,1,0,2021-03-15

- `\D`: 숫자가 아닌 모든 문자에 대응하는 표현

In [ ]:
# 발행년도 열의 데이터에서 숫자 이외의 값이 포함된 행 추출
invalid_number = ns_book4['발행년도'].str.contains(r'\D', na=True)
print(invalid_number.sum())
ns_book4[invalid_number].head()

1777

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
19138,19565,단국강토,홍태수 저,매일경제신문사,1988.,9788974420031,,NaN,NaN,511.1,1,1,2019-12-19
19227,19736,삼성의 역사,송부웅 撰,삼양,단기4334[2001],9788985464369,,0,NaN,911.02,1,1,2019-12-06
26097,26812,배고픈 애벌레,에릭 칼 글·그림 ;이희재 옮김,더큰컴퍼니,[2019],9788959514083,,NaN,NaN,843,1,0,2019-08-12
29817,30586,(The) Sopranos sessions,"Matt Zoller Seitz,$eAlan Sepinwall,$eLaura Lip...",Harry N Abrams Inc,2019.,9781419734946,,NaN,NaN,326.76,1,0,2019-06-13
29940,30709,다음엔 너야,에른스트 얀들 글;노르만 융에 그림;박상순 옮김,비룡소,2018.,9788949110646,9788949110004,7,NaN,853,1,9,2019-06-04

In [23]:
# 연도 앞 뒤의 문자를 제외하는 정규표현식
ns_book5 = ns_book4.replace({'발행년도':r'.*(\d{4}).*'}, r'\1', regex=True)
ns_book5[invalid_number].head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
19138,19565,단국강토,홍태수 저,매일경제신문사,1988,9788974420031,,NaN,NaN,511.1,1,1,2019-12-19
19227,19736,삼성의 역사,송부웅 撰,삼양,2001,9788985464369,,0,NaN,911.02,1,1,2019-12-06
26097,26812,배고픈 애벌레,에릭 칼 글·그림 ;이희재 옮김,더큰컴퍼니,2019,9788959514083,,NaN,NaN,843,1,0,2019-08-12
29817,30586,(The) Sopranos sessions,"Matt Zoller Seitz,$eAlan Sepinwall,$eLaura Lip...",Harry N Abrams Inc,2019,9781419734946,,NaN,NaN,326.76,1,0,2019-06-13
29940,30709,다음엔 너야,에른스트 얀들 글;노르만 융에 그림;박상순 옮김,비룡소,2018,9788949110646,9788949110004,7,NaN,853,1,9,2019-06-04

In [25]:
unknown_year = ns_book5['발행년도'].str.contains(r'\D', na=True)
ns_book5.loc[unknown_year, '발행년도'] = -1
ns_book5 = ns_book5.astype({'발행년도':'int64'})

- `gt()` 메서드: 지정된 값보다 큰 값 검사(>)  
- `ge()` 메서드: 지정된 값보다 크거나 같은 값 검사(>=)    
- `lt()` 메서드: 지정된 값보다 작은 값 검사(<)  
- `le()` 메서드: 지정된 값보다 작거나 같은 값 검사(<=)  
- `eq()` 메서드: 지정된 값과 같은 값 검사(==)  
- `ne()` 메서드: 지정된 값과 같지 않은 값 검사(!=)

In [30]:
# 연도가 이상한 행의 발행년도 값을 -1로 변경
dangun_yy_rows = ns_book5['발행년도'].gt(4000)
ns_book5.loc[dangun_yy_rows, '발행년도'] = ns_book5.loc[dangun_yy_rows, '발행년도'] - 2333
dangun_year = ns_book5['발행년도'].gt(4000)
ns_book5.loc[dangun_year, '발행년도'] = -1

old_books = ns_book5['발행년도'].gt(0) & ns_book5['발행년도'].lt(1900)
ns_book5.loc[old_books, '발행년도'] = -1
ns_book5['발행년도'].eq(-1).sum()

85

- 누락된 정보 채우기 예시

In [ ]:
# 누락된 값이 있는 행의 개수
na_rows = ns_book5['도서명'].isna() | ns_book5['저자'].isna() | ns_book5['출판사'].isna() | ns_book5['발행년도'].eq(-1)
print(na_rows.sum())

5267

In [32]:
import requests
from bs4 import BeautifulSoup

In [35]:
# 도서명을 가져오는 함수
def get_book_title(isbn):

    url = 'http://www.yes24.com/Product/Search?domain=BOOK&query={}'

    res = requests.get(url.format(isbn))
    soup = BeautifulSoup(res.text, 'html.parser')
    title = soup.find('a', attrs={'class':'gd_name'}).get_text()
    return title

get_book_title(9791191266054)

'골목의 시간을 그리다'

In [36]:
# 같은 방식으로 저자, 출판사, 발행 년도를 가져오는 함수 
import re

def get_book_info(row):
    title = row['도서명']
    author = row['저자']
    pub = row['출판사']
    year = row['발행년도']

    url = 'http://www.yes24.com/Product/Search?domain=BOOK&query={}'
    r = requests.get(url.format(row['ISBN']))
    soup = BeautifulSoup(r.text, 'html.parser')

    try:
        if pd.isna(title):
            title = soup.find('a', attrs={'class':'gd_name'}).get_text()
    except AttributeError:
        pass 

    try:
        if pd.isna(author):
            authors = soup.find('span', attrs={'class':'info_auth'}).find_all('a')
            author_list = [auth.get_text() for auth in authors]
            author = ','.join(author_list)
    except AttributeError:
        pass 

    try:
        if pd.isna(pub):
            pub = soup.find('span', attrs={'class':'info_pub'}).find('a').get_text()
    except AttributeError:
        pass 

    try:
        if year == -1:
            year_str = soup.find('span', attrs={'class':'info_date'}).get_text()
            year = re.findall(r'\d{4}', year_str)[0]
    except AttributeError:
        pass

    return title, author, pub, year

In [37]:
updated_sample = ns_book5[na_rows].head(2).apply(get_book_info, axis=1, result_type='expand')
updated_sample

               0           1           2     3
78    아산 정주영 레거시         김화진  서울대학교출판문화원  2021
265  골목의 시간을 그리다  정명섭.김효찬 지음      초록비책공방  2021