In [4]:
# 남산도서관 데이터 다운로드
import gdown
gdown.download('https://bit.ly/3RhoNho', 'ns_202104.csv', quiet=False)  # quiet=False: 진행 사항을 표시

Downloading...
From: https://bit.ly/3RhoNho
To: c:\til\ns_202104.csv
100%|██████████| 57.6M/57.6M [00:04<00:00, 12.4MB/s]

'ns_202104.csv'

In [5]:
import pandas as pd

ns_df = pd.read_csv('ns_202104.csv', low_memory=False)  # low_memory=False: 각 컬럼의 타입을 정확하게 추론하기 위한 옵션
ns_df.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN

In [6]:
# 'Unnamed: 13' 컬럼 제외하기
ns_book = ns_df.loc[:, '번호':'등록일자']
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19

In [9]:
print(ns_df.columns)
print(ns_df.columns[0])

Index(['번호', '도서명', '저자', '출판사', '발행년도', 'ISBN', '세트 ISBN', '부가기호', '권',
       '주제분류번호', '도서권수', '대출건수', '등록일자', 'Unnamed: 13'],
      dtype='object')
번호

- Index 클래스를 비롯하여 판다스 배열 성격의 객체는 어떤 값과 비교할 때 자동으로 배열에 있는 모든 원소와 한 번씩 비교 -> **원소별 비교**

In [12]:
print(ns_df.columns != 'Unnamed: 13')
print(type(ns_df.columns != 'Unnamed: 13'))

[ True  True  True  True  True  True  True  True  True  True  True  True
  True False]
<class 'numpy.ndarray'>

- 이렇게 생성된 객체의 결과는 넘파이 배열(Numpy array)

In [13]:
# 비교 결과로 배열 생성
selected_columns = ns_df.columns != 'Unnamed: 13'
ns_book = ns_df.loc[:, selected_columns]    # 열의 조건으로 unnamed가 아닌 열만 추출
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19

- `drop()` 메서드: 데이터프레임의 행이나 열을 삭제하는 메서드
    - 첫 번째 매개변수로는 삭제하려는 행/열의 이름, `axis` 매개변수가 0이면 행, 1이면 열을 의미

In [15]:
ns_book = ns_df.drop(['부가기호', 'Unnamed: 13'], axis = 1)   
ns_book.head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,1,0,2021-03-19

pd의 메서드의 매개변수 중 `inplace` 매개변수를 `True`로 지정하면 수정한 결과를 바로 데이터프레임에 반영 가능

In [16]:
ns_book.drop('주제분류번호', axis=1, inplace=True)
ns_book.head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,권,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,1,0,2021-03-19

- `dropna()` 메서드: `NaN`이 포함된 행 또는 열을 삭제

In [ ]:
ns_book = ns_df.dropna(axis = 1)    # NaN이 하나라도 포함된 열 삭제
ns_book.head(2)

   번호           ISBN  도서권수  대출건수        등록일자
0   1  9788937444319     1     0  2021-03-19
1   2  9791190123969     1     0  2021-03-19

In [18]:
ns_book = ns_df.dropna(axis=1, how='all')   # 모든 값이 NaN인 열을 삭제하려면 how를 'all'로 지정
ns_book.head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19

In [20]:
ns_book2 = ns_book.drop([0,1])  # 0, 1번째 행 삭제
ns_book2.head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19

- `duplicated()` 메서드: 중복된 행 중에서 처음 행을 제외한 나머지 행은 `True`,  
                        그 외에 중복되지 않은 나머지 모든 행은 `False`로 표시

In [23]:
print(ns_book.duplicated())
print(sum(ns_book.duplicated()))   # 0 -> True인 값이 없음을 의미하므로 중복된 행이 없음

0         False
1         False
2         False
3         False
4         False
          ...
401677    False
401678    False
401679    False
401680    False
401681    False
Length: 401682, dtype: bool
0

- 일부 열을 기준으로 중복된 행을 찾으려면 `subset` 매개변수에 기준 열을 나열

In [22]:
sum(ns_book.duplicated(subset=['도서명','저자','ISBN']))

22096

In [ ]:
dup_rows = ns_book.duplicated(subset=['도서명','저자','ISBN'], keep=False)  # keep=False 옵션은 중복되는 모든 행에 대해 True로 표시
ns_book3 = ns_book[dup_rows]
ns_book3.head(3)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
109,110,파친코,이민진 지음 ;이미정 옮김,문학사상,2018,9788970129815,9788970129808,0,1,843.6,1,0,2021-03-12
110,111,파친코,이민진 지음 ;이미정 옮김,문학사상,2018,9788970129822,9788970129808,0,2,843.6,1,0,2021-03-12
111,112,보건교사 안은영 :정세랑 장편소설,지은이: 정세랑,민음사,2021,9788937479953,NaN,0,NaN,813.7,1,0,2021-03-12

In [ ]:
# groupby() 메서드 사용예시
count_df = ns_book[['도서명','저자','ISBN','권','대출건수']]

# by 매개변수를 통해 기준이 되는 열 지정
# dropna=False로 지정하면 NaN이 있는 행도 포함하여 계산
group_df = count_df.groupby(by=['도서명','저자','ISBN','권'], dropna=False)
loan_count = group_df.sum()

In [27]:
loan_count = count_df.groupby(by=['도서명','저자','ISBN','권'], dropna=False).sum()
loan_count.head()

                                                                                           대출건수
도서명                                            저자                       ISBN          권
(꼭 필요한 것부터 쉽게 배우는) 자신만만 블로그 차근차근 배우기           김상현 지음                   9788955025637 NaN    38
(맨처음 배우는) 세상의 직업                               엘레오노라 바르소티 글 ·그림 ;김태은 옮김 9788992924146 NaN    10
(영잘원 리스닝과 패턴 영어의 절묘한 만남으로 태어난 ) 리스닝 ABC : 입문편  JD Kim 지음                9788993466089 NaN     4
(즉석에서 바로바로 활용하는) 일상생활 베트남어 첫걸음                 FL4U컨텐츠 지음               9788971728000 NaN     3
,에게                                            이기린(이진희)                 9791196137014 NaN     0

- `~` 연산자를 사용하면 중복된 행을 `True`로 표시한 `boolean` 배열을 반전 가능

In [28]:
dup_rows = ns_book.duplicated(subset=['도서명','저자','ISBN','권'])

unique_rows = ~dup_rows 

# 중복되지 않는 행만 copy
ns_book3 = ns_book[unique_rows].copy()

In [ ]:
sum(ns_book3.duplicated(subset=['도서명','저자','ISBN','권']))  # sum의 결과가 0이므로 중복되는 행 없음

0

- `set_index()` 메서드: 지정한 열을 기준으로 인덱스를 설정하는 메서드

In [30]:
ns_book3.set_index(['도서명','저자','ISBN','권'], inplace=True)
ns_book3.head()

,,,,번호,출판사,발행년도,세트 ISBN,부가기호,주제분류번호,도서권수,대출건수,등록일자
도서명,저자,ISBN,권,,,,,,,,,
인공지능과 흙,김동훈 지음,9788937444319,NaN,1,민음사,2021,NaN,NaN,NaN,1,0,2021-03-19
가짜 행복 권하는 사회,김태형 지음,9791190123969,NaN,2,갈매나무,2021,NaN,NaN,NaN,1,0,2021-03-19
나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,9788968332982,NaN,3,블랙피쉬,2021,NaN,NaN,NaN,1,0,2021-03-19
예루살렘 해변,"이도 게펜 지음, 임재희 옮김",9788970759906,NaN,4,문학세계사,2021,NaN,NaN,NaN,1,0,2021-03-19
김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,9788934990833,NaN,5,김영사,2021,NaN,NaN,NaN,1,0,2021-03-19

- `update()` 메서드: 다른 데이터프레임을 이용해 원본 데이터프레임의 값을 업데이트하는 메서드

In [31]:
ns_book3.update(loan_count)
ns_book3.head()

C:\Users\user\AppData\Local\Temp\ipykernel_11524\3051281402.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  ns_book3.update(loan_count)

,,,,번호,출판사,발행년도,세트 ISBN,부가기호,주제분류번호,도서권수,대출건수,등록일자
도서명,저자,ISBN,권,,,,,,,,,
인공지능과 흙,김동훈 지음,9788937444319,NaN,1,민음사,2021,NaN,NaN,NaN,1,0,2021-03-19
가짜 행복 권하는 사회,김태형 지음,9791190123969,NaN,2,갈매나무,2021,NaN,NaN,NaN,1,0,2021-03-19
나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,9788968332982,NaN,3,블랙피쉬,2021,NaN,NaN,NaN,1,0,2021-03-19
예루살렘 해변,"이도 게펜 지음, 임재희 옮김",9788970759906,NaN,4,문학세계사,2021,NaN,NaN,NaN,1,0,2021-03-19
김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,9788934990833,NaN,5,김영사,2021,NaN,NaN,NaN,1,0,2021-03-19

- `reset_index()` 메서드: 데이터프레임의 인덱스를 재설정하는 메서드

In [32]:
ns_book4 = ns_book3.reset_index()
ns_book4.head()

,도서명,저자,ISBN,권,번호,출판사,발행년도,세트 ISBN,부가기호,주제분류번호,도서권수,대출건수,등록일자
0,인공지능과 흙,김동훈 지음,9788937444319,NaN,1,민음사,2021,NaN,NaN,NaN,1,0,2021-03-19
1,가짜 행복 권하는 사회,김태형 지음,9791190123969,NaN,2,갈매나무,2021,NaN,NaN,NaN,1,0,2021-03-19
2,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,9788968332982,NaN,3,블랙피쉬,2021,NaN,NaN,NaN,1,0,2021-03-19
3,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",9788970759906,NaN,4,문학세계사,2021,NaN,NaN,NaN,1,0,2021-03-19
4,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,9788934990833,NaN,5,김영사,2021,NaN,NaN,NaN,1,0,2021-03-19

In [33]:
ns_book4 = ns_book4[ns_book.columns]    # 원래 데이터의 컬럼과 일치하는 컬럼만 선택
ns_book4.head(3)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19

In [34]:
ns_book4.to_csv('ns_book4.csv', index=False)    # csv파일로 저장