- API(application programming interface): 두 프로그램이 서로 대화하기 위한 방법을 정의한 것

- 웹 기반 API의 예시

> 프로그램 A -> (데이터 요청: HTTP) -> 프로그램 B  
> 프로그램 A <- (데이터 전송: CSV, JSON, XML ..) <- 프로그램 B

- JSON(Javascript object notation)

In [1]:
# json은 파이썬 딕셔너리와 비슷한 형식
d = {"name" : "혼자 공부하는 데이터 분석"}
print(d['name'])

혼자 공부하는 데이터 분석

In [4]:
# 파이썬 객체 (딕셔너리) -> json
import json
d_json = json.dumps(d, ensure_ascii=False)
print(d_json)
print(type(d_json))

{"name": "혼자 공부하는 데이터 분석"}
<class 'str'>

In [5]:
# json -> 딕셔너리
d2 = json.loads(d_json)
print(d2)
print(type(d2))

{'name': '혼자 공부하는 데이터 분석'}
<class 'dict'>

In [6]:
# json 배열
d4_json = """   
[   
    {"name" : "혼자 공부하는 데이터 분석", "author" : "박해선", "year" : 2022},
    {"name" : "혼자 공부하는 머신러닝+딥러닝", "author" : "박해선", "year" : 2020}
]
"""
d4 = json.loads(d4_json)
print(d4[0]["name"])    # json 배열 접근 방식

혼자 공부하는 데이터 분석

In [8]:
# json -> dataframe
from io import StringIO
import pandas as pd

pd.read_json(StringIO(d4_json))

               name author  year
0    혼자 공부하는 데이터 분석    박해선  2022
1  혼자 공부하는 머신러닝+딥러닝    박해선  2020

In [9]:
# dict -> dataframe
pd.DataFrame(d4)

               name author  year
0    혼자 공부하는 데이터 분석    박해선  2022
1  혼자 공부하는 머신러닝+딥러닝    박해선  2020

- xml(extensible markup language): 컴퓨터와 사람이 모두 읽고 쓰기 편한 마크업 언어
- xml은 element들이 계층 구조를 이루며 정보를 표현하고, element는 시작 tag와 종료 tag로 감싸져 있음  
ex> `<name>원종현</name>`  
element - 원종현  
시작 tag: `<name>`  
종료 tag: `</name>`

- HTTP GET 방식  : 호출하는 URL 뒤에 파라미터를 연결하는 방식  
- 파라미터와 값은 '=', 파라미터 사이는 '&', 호출 URL과 파라미터는 '?'로 연결  
ex> `http://datalib.kr/items?authkey=******&startdt=2026-08-10`

- requests 패키지: 파이썬에서 URL을 호출하여 데이터를 받을 수 있는 방법

```python
import requests

url = ""  
response = requests.get(url)
print(type(response))
json_data = response.json() # 웹 서버로부터 받은 json 문자열을 파이썬 객체(딕셔너리)로 변환
```
- get() 함수가 반환하는 값은 requests 패키지의 Response 클래스